/**
 * Route info lookup table, built from SL GTFS static routes.txt.
 * Generated by: npm run process-shapes -- --city stockholm
 * Reads from: public/shapes/stockholm/routes.json
 */

import fs   from 'node:fs';
import path from 'node:path';

export interface RouteInfo {
  name:          string;   // route_short_name
  type:          number;   // GTFS route_type (700=bus, 900=tram, 100=train, 1000=ferry, 401=metro)
  bgColor:       string;   // #RRGGBB  (from route_color or type fallback)
  fgColor:       string;   // #RRGGBB  (from route_text_color or type fallback)
}

// GTFS route_type → transport mode label used by the app
export const ROUTE_TYPE_MODE: Record<number, string> = {
  100:  'train',
  400:  'train',  // metro (underground)
  401:  'train',
  700:  'bus',
  900:  'tram',
  1000: 'ferry',
  1200: 'ferry',
};

// Fallback colors when GTFS doesn't specify
const TYPE_COLOR: Record<number, { bg: string; fg: string }> = {
  100:  { bg: '#7c3aed', fg: '#ffffff' },  // Train  — purple
  400:  { bg: '#1d4ed8', fg: '#ffffff' },  // Metro  — blue
  401:  { bg: '#1d4ed8', fg: '#ffffff' },
  700:  { bg: '#0f766e', fg: '#ffffff' },  // Bus    — teal
  900:  { bg: '#0284c7', fg: '#ffffff' },  // Tram   — sky
  1000: { bg: '#0891b2', fg: '#ffffff' },  // Ferry  — cyan
};
const FALLBACK = { bg: '#374151', fg: '#ffffff' };

let cache: Map<string, RouteInfo> | null = null;

export function getRoutes(): Map<string, RouteInfo> {
  if (cache) return cache;

  try {
    const filePath = path.resolve(process.cwd(), 'public/shapes/stockholm/routes.json');
    const raw      = JSON.parse(fs.readFileSync(filePath, 'utf8')) as {
      routes: Record<string, { name: string; type: number; color?: string; textColor?: string }>;
    };

    cache = new Map(
      Object.entries(raw.routes).map(([id, r]) => {
        const fb = TYPE_COLOR[r.type] ?? FALLBACK;
        return [id, {
          name:    r.name,
          type:    r.type,
          bgColor: r.color     ? `#${r.color}`     : fb.bg,
          fgColor: r.textColor ? `#${r.textColor}` : fb.fg,
        }];
      }),
    );
  } catch {
    // routes.json not yet built — shapes script hasn't been run for Stockholm
    cache = new Map();
  }

  return cache;
}
